[package]
name = "gstprerollvalve"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
gstreamer = "0.22"
gstreamer-base = "0.22"
gstreamer-video = "0.22"
glib = "0.19"
once_cell = "1.0"

[lib]
name = "gstprerollvalve"
crate-type = ["cdylib", "rlib"]

